CREATE TABLE cards (
    number BIGINT UNIQUE NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    type VARCHAR(255) NOT NULL DEFAULT 'COMUM',
    user_id BIGINT NOT NULL,
    record BIGSERIAL NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
