-- Script para criar tabelas no H2 para testes
-- Cria a sequence
CREATE SEQUENCE IF NOT EXISTS card_number_seq START WITH 1;

-- Cria a tabela users sem o tipo customizado
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(255) NOT NULL DEFAULT 'USER',
    password VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

-- Cria a tabela cards
CREATE TABLE IF NOT EXISTS cards (
    number BIGINT UNIQUE NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    type VARCHAR(255) NOT NULL DEFAULT 'COMUM',
    user_id BIGINT NOT NULL,
    record BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
